### ISSUE TITLE
Need help with basic query fetching

### ISSUE THREAD

**Issue by sunandosamaddar** [googleapis/python-datastore#14]
**google-cloud-datastore version: 1.10.0**
Code e.g.:

```
client = datastore.Client(
        project=project,
        namespace='default',
        credentials=credentials)
query = client.query(kind='User')
query.add_filter('username', '=', username)
result_entity = list(query.fetch(limit=2)).pop()
```

The code fails at last line whether using `limit` or not.

**Comment by IlyaFaer** [comment]
@sunandosamaddar, could you provide a traceback please?!

**Comment by sunandosamaddar** [comment]
1. ```
Traceback (most recent call last):
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/fastapi/routing.py", line 133, in app
    raw_response = await dependant.call(**values)
  File "./users.py", line 126, in login_for_access_token
    user = authenticate_user(form_data.username, form_data.password)
  File "./users.py", line 77, in authenticate_user
    user = get_user(username, project, kfpath)
  File "./users.py", line 70, in get_user
    result_entity = list(query.fetch()).pop()
IndexError: pop from empty list
```

2. ```
Traceback (most recent call last):
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/sunandosamaddar/opt/miniconda3/lib/python3.7/site-packages/fastapi/routing.py", line 133, in app
    raw_response = await dependant.call(**values)
  File "./users.py", line 126, in login_for_access_token
    user = authenticate_user(form_data.username, form_data.password)
  File "./users.py", line 77, in authenticate_user
    user = get_user(username, project, kfpath)
  File "./users.py", line 70, in get_user
    result_entity = list(query.fetch(limit=50, offset=0)).pop()
```

**Comment by IlyaFaer** [comment]
The data isn't found at all, even in absence of a limit. I've checked couple of system tests (for [example](https://github.com/googleapis/python-datastore/blob/672ba3e6bc056991018590e99466d4b68459b6a3/tests/system/test_system.py#L213-L230)) - they are okay, though they're working in the same way: `list` from `fetch()` with `limit` and filter.

So the problem is most likely caused by lack of data or wrong filters. Please, check you're writing into DB code, presence of the data (by running query without filters, etc.) and current filters
